// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.

package bootstrap

import (
	webDnsRepository "local_dns_proxy/internal/infrastructure/persistence"
	webDnsService "local_dns_proxy/internal/application/dns"
	webDnsHandler "local_dns_proxy/internal/interfaces/web"

	"local_dns_proxy/internal/infrastructure/query"
	"gorm.io/gorm"
)

type appContext struct {
	WebDnsHandler *webDnsHandler.DnsHandler
}

func NewAppContext(db *gorm.DB) *appContext {
	webDnsRepo := &webDnsRepository.WebDnsRepository{DB: db, Q: query.Q}
	webDnsService := &webDnsService.WebDnsService{Repo: webDnsRepo}
	webDnsHandler := &webDnsHandler.DnsHandler{Service: webDnsService}

	return &appContext{
		WebDnsHandler: webDnsHandler,
	}
}